apiVersion: v1
kind: Service
metadata:
  name: predictor-service
  namespace: default
  labels:
    app: predictor-service
    tier: prediction
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: predictor-service
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
    - name: metrics
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP